package com.devbp.syncspace.domain.dtos;

import com.devbp.syncspace.domain.InvoiceStatus;
import jakarta.persistence.Column;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CreateInvoiceRequest {

    private long clientId;

    //autogenerated
    private String invoiceNumber;

    @NotNull(message = "Due Date is required")
    private LocalDate dueDate;

    @NotNull(message = "Total amount is required")
    @PositiveOrZero
    private double totalAmount;

    @PositiveOrZero
    private double taxAmount;

    private InvoiceStatus invoiceStatus;

    //create check if invoice status = PAID then the next 2 field must be entered
    private LocalDateTime paymentDate;

    private String paymentMethod;

    private String notes;

}
